const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function createLoadingStatus({title='Loading data',collapseDelay=1400}={}){
  const header=document.querySelector('.header'),host=document.createElement('div');host.className='ls-header';host.innerHTML='<button type="button" class="ls-connection" data-state="unknown" role="status" aria-label="Connection status: Unknown"><span class="ls-dot"></span><span class="ls-label">Unknown</span></button><span class="ls-last">Not checked</span>';header?.appendChild(host);
  const panel=document.createElement('section');panel.className='ls-panel';panel.hidden=true;panel.setAttribute('aria-live','polite');panel.innerHTML='<div class="ls-top"><div><div class="ls-title"></div><div class="ls-meta"></div></div><div class="ls-summary"></div></div><div class="ls-track" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="ls-bar"></div></div><div class="ls-task"></div><div class="ls-checklist"></div><div class="ls-error" hidden></div><div class="ls-cache" hidden></div><div class="ls-actions"><button type="button" class="ls-retry" hidden>Retry</button><button type="button" class="ls-dismiss" hidden>Dismiss</button></div>';
  const nav=document.querySelector('.nav');(nav||header)?.insertAdjacentElement('afterend',panel);
  let steps=[],completed=new Set(),failed=new Set(),warning=new Set(),activeIndex=-1,retryAction=null,active=false,collapseTimer=null,lastConnection={state:'unknown',label:'Unknown'},startTime=0,tickTimer=null,stepDetails=new Map();
  const q=s=>panel.querySelector(s),connection=host.querySelector('.ls-connection'),last=host.querySelector('.ls-last');
  function percentage(){return steps.length?completed.size/steps.length*100:0}
  function formatDuration(seconds){seconds=Math.max(0,Math.round(seconds));if(seconds<60)return`${seconds}s`;const m=Math.floor(seconds/60),s=seconds%60;return`${m}m ${String(s).padStart(2,'0')}s`}
  function timingText(){if(!active||!startTime)return'';const elapsedS=(Date.now()-startTime)/1000;if(!completed.size||completed.size>=steps.length)return` · ${formatDuration(elapsedS)} elapsed`;const avgPerStep=elapsedS/completed.size,remainingS=avgPerStep*(steps.length-completed.size);return` · ~${formatDuration(remainingS)} remaining`}
  function render(){const pct=percentage(),display=Math.round(pct),position=Math.max(0,activeIndex+1);q('.ls-title').innerHTML=`${active?'<span class="ls-spinner"></span>':''}${esc(panel.dataset.operation||title)}`;q('.ls-meta').textContent=steps.length?`${position||completed.size} of ${steps.length} — ${display}%${timingText()}`:'';q('.ls-summary').textContent=steps.length?`Completed ${completed.size} · Failed ${failed.size} · Warnings ${warning.size}`:'';q('.ls-bar').style.width=`${Math.min(100,pct)}%`;q('.ls-track').setAttribute('aria-valuenow',String(display));q('.ls-task').textContent=activeIndex>=0?`Current task: ${steps[activeIndex]}`:'';q('.ls-checklist').innerHTML=steps.map((step,i)=>{const state=failed.has(i)?'failed':warning.has(i)?'warning':completed.has(i)?'complete':i===activeIndex?'active':'pending',icon=state==='complete'?'✓':state==='failed'?'✕':state==='warning'?'!':state==='active'?'…':'○',detail=stepDetails.get(i);return`<div class="ls-step" data-state="${state}">${icon} ${i+1}. ${esc(step)}${detail?`<div class="ls-step-detail">${esc(detail)}</div>`:''}</div>`}).join('')}
  function setConnection(state,label,detail=''){lastConnection={state,label};connection.dataset.state=state;connection.querySelector('.ls-label').textContent=label;connection.setAttribute('aria-label',`Connection status: ${label}${detail?`. ${detail}`:''}`);last.textContent=detail||`Last checked: ${new Date().toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}`}
  async function checkConnection({zendesk=false}={}){if(navigator.onLine===false){setConnection('offline','Offline','Browser network unavailable');return{success:false,state:'offline'}}setConnection('checking','Checking','Checking local server');try{const response=await fetch('/api/health',{cache:'no-store'});if(!response.ok)throw Object.assign(new Error(`GET /api/health returned HTTP ${response.status}`),{endpoint:'/api/health',status:response.status});const health=await response.json();if(zendesk){const zr=await fetch('/api/health/zendesk',{cache:'no-store'}),zd=await zr.json();if(!zr.ok||zd.zendesk!=='connected'){const updated=zd.lastSuccessfulUpdate?new Date(zd.lastSuccessfulUpdate):null,age=updated&&Number.isFinite(updated.valueOf())?`${Math.max(0,Math.round((Date.now()-updated)/60000))} minute(s) old`:'age unavailable',datasets=(zd.cachedDatasets||[]).join(', ')||'none',failed=(zd.failedDatasets||[]).join(', ')||'none',detail=zd.cachedDataAvailable?`Cached: ${datasets}; last successful update ${updated?.toLocaleString()||'unavailable'} (${age}); failed/stale: ${failed}`:'Zendesk connection unavailable; no cached data';setConnection('degraded','API Degraded',detail);q('.ls-cache').hidden=false;q('.ls-cache').textContent=`API Degraded — displaying cached data. ${detail}`;return{success:true,state:'degraded',health,zendesk:zd}}}setConnection('connected','API Connected',`Last checked: ${new Date().toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}`);return{success:true,state:'connected',health}}catch(error){error.endpoint ||= '/api/health';setConnection('server-offline','Server Offline','Local server unavailable');throw error}}
  function start(operation,newSteps,{retry}={}){clearTimeout(collapseTimer);clearInterval(tickTimer);steps=[...newSteps];completed.clear();failed.clear();warning.clear();stepDetails.clear();activeIndex=-1;retryAction=retry||retryAction;active=true;startTime=Date.now();panel.hidden=false;panel.className='ls-panel ls-active';panel.dataset.operation=operation;q('.ls-error').hidden=true;q('.ls-cache').hidden=true;q('.ls-retry').hidden=true;q('.ls-dismiss').hidden=true;render();tickTimer=setInterval(render,1000)}
  function begin(index){activeIndex=index;stepDetails.delete(index);render()}function complete(index,{state='complete',detail=''}={}){if(state==='warning')warning.add(index);completed.add(index);activeIndex=index;stepDetails.delete(index);if(detail){q('.ls-cache').hidden=false;q('.ls-cache').textContent=detail}render()}
  function setStepDetail(index,text){if(text)stepDetails.set(index,text);else stepDetails.delete(index);render()}
  function fail(index,error,{cached=false,continueLoading=false}={}){failed.add(index);activeIndex=index;if(cached)warning.add(index);const endpoint=error?.endpoint||'',status=error?.status||'',message=error?.message||String(error),source=endpoint?`\n${endpoint}${status?` returned HTTP ${status}`:' could not be reached'}`:'';q('.ls-error').hidden=false;q('.ls-error').textContent=`Loading failed at step ${index+1} of ${steps.length}\n${steps[index]} could not be completed.${source}\n${message}`;if(cached){q('.ls-cache').hidden=false;q('.ls-cache').textContent='API Degraded — displaying cached data. This data is not live.';setConnection('degraded','API Degraded','Displaying cached data')}q('.ls-retry').hidden=!retryAction;active=continueLoading;if(!continueLoading)clearInterval(tickTimer);panel.className=`ls-panel ${continueLoading?'ls-active':'ls-failed'}`;render()}
  function finish(message,{state='success',collapse=true,cacheDetail=''}={}){active=false;clearInterval(tickTimer);activeIndex=steps.length-1;panel.dataset.operation=message;panel.className=`ls-panel ls-${state}`;if(cacheDetail){q('.ls-cache').hidden=false;q('.ls-cache').textContent=cacheDetail}q('.ls-dismiss').hidden=false;render();if(collapse&&state==='success')collapseTimer=setTimeout(()=>panel.classList.add('ls-compact'),collapseDelay)}
  function setRetry(fn){retryAction=fn;q('.ls-retry').hidden=!fn}function dismiss(){panel.hidden=true;clearInterval(tickTimer)}q('.ls-retry').onclick=()=>retryAction?.();q('.ls-dismiss').onclick=dismiss;connection.onclick=()=>checkConnection({zendesk:true}).catch(()=>{});window.addEventListener('online',()=>checkConnection().catch(()=>{}));window.addEventListener('offline',()=>setConnection('offline','Offline','Browser network unavailable'));document.addEventListener('visibilitychange',()=>{if(!document.hidden&&lastConnection.state==='server-offline')checkConnection().catch(()=>{})});
  return{start,begin,complete,fail,finish,setRetry,dismiss,checkConnection,setConnection,setStepDetail,get isActive(){return active},get percentage(){return percentage()},get state(){return lastConnection}};
}
